### ISSUE TITLE
Does not exit cleanly when server is shut down.

### ISSUE THREAD

**Issue by akayami** [roccomuso/memorystore#11]
I'm trying to use this to do some tests. I use mocha, with a beforeEach and afterEach stoping and starting express instance that also uses your module for sessions. It seems your intervals linger on after the http server containing the express application is shut down. In short, mocha does not exit at the end of its tests. I need to control-c it. I have not analyzed your code, but I assume you do not clear some Intervals/Timeouts when the shutdown is issued.

**Comment by roccomuso** [comment]
That logic is up to the user.
There's the `stopInterval` method: https://github.com/roccomuso/memorystore/blob/master/lib/memorystore.js#L280
