### ISSUE TITLE
Handling touch session that is removed priviously

### ISSUE THREAD

**Issue by shayantabatabaee** [roccomuso/memorystore#13]
Hi, 
I use **memorystore** with **express-session** and **express** in NodeJs. Recently  I met an issue in `touch` method of sessions, assume situation that I made two requests from my server to another server, and just before of receiving second response I destroy my client session, the touch method will throw `Unexpected Json u at position 0` due to `store.get(sid)` is `undefined`. And the error will throw back to my error middlewares. So I think there is no need to touch `undefined` session.

**Comment by shayantabatabaee** [comment]
Thanks dear @roccomuso for merging. This issue has been fixed due to commit #14 . Please release a version if you wish.

**Comment by roccomuso** [comment]
Released new version `v1.6.2`
