### ISSUE TITLE
Every time an exception occurs in the expressjs application, memorystore is cleared

### ISSUE THREAD

**Issue by bozzmob** [roccomuso/memorystore#18]
Hi,

Every time an exception occurs in the expressjs application, memorystore is cleared. The exception is handled as well in the catch block(ex- in case of mysql exception - key already exists).

I am not sure why this is happening or is it expected?

This is my configuration-
```
var store = new BetterMemoryStore({
  expires: 60 * 60 * 1000,
  debug: true,
});
app.use(
  sess({
    name: "JSESSION",
    secret: "SOMEPRIVATEKEY",
    store: store,
    resave: true,
    saveUninitialized: true,
  })
);
```

Is it because of debug:true? What am I missing? Please help.

Also, when I restart the application (pm2 reload), the store is cleared, this is expected?

```
   "body-parser": "^1.19.0",
    "connect-flash": "^0.1.1",
    "cookie-parser": "~1.4.3",
    "cron": "^1.7.2",
    "debug": "~2.6.9",
    "ejs": "~2.5.7",
    "express": "~4.16.0",
    "express-session": "^1.16.2",
    "http-errors": "~1.6.2",
    "mysql": "^2.17.1",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "redis": "^2.8.0",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.8",
    "winston": "^3.2.1"
```

**Comment by roccomuso** [comment]
What do you catch exactly? it shouldn't be cleared if the exception is catched and the process doesn't exit.

If the application pm2 reloads the process, the store is cleared, the process is restarted and MemoryStore kept everything in the process memory, that is expected.

**Comment by bozzmob** [comment]
Let's say this is the implementation-

```
// rest of the code
connection.query(`INSERT INTO ${table} SET ?`, object, function (
          err,
          result
        ) {
          if (err) {
            logger.error(
              `INSERT SQL ERROR - ${err} | table - ${table} | object - ${JSON.stringify(
                object
              )} `,
              {
                labels: ["MYSQL", "INSERT"],
              }
            );
            connection.release();
            reject(err);
          }

// rest of the code
```

So, since there is a `reject(err);` and which is not caught in the code using it, this may be causing the error.
So, an uncaught rejection can cause this error right?

**Comment by roccomuso** [comment]
Yes. uncaught exception make the process crash. So everything is cleared.

**Comment by bozzmob** [comment]
2 weeks through, I wasn't able to figure out the cause of the issue, and I'm narrating the issue here and I figure it out. Thank you for your time :)

**Comment by bozzmob** [comment]
I was wondering, it would be nice if there was an option to persist the store once every 'x' minutes or whenever the value changes in the memorystore. This would make the memory store resilient across crashes or reloads.
What do you think?

**Comment by roccomuso** [comment]
This is called memorystore because it's in memory.
You can write that logic yourself if you want to.

Or consider using other store mechanism that relies on persistent storage: https://github.com/expressjs/session#compatible-session-stores

**Comment by bozzmob** [comment]
I get it :) Thank you for your time.
