### ISSUE TITLE
Example of using the "dispose" option.

### ISSUE THREAD

**Issue by RiaanJacobs76** [roccomuso/memorystore#2]
Hi, I'm not quite sure how this works. From what I see this can be used to call a function but are you able to pass that function parameters and can these parameters be values stored in the session about to be dropped from the cache? Would it be possible to show us an example?

**Comment by roccomuso** [comment]
That dispose function is passed straight to the `lru-cache` module.

> Function that is called on items when they are dropped from the cache. This can be handy if you want to close file descriptors or do other cleanup tasks when items are no longer accessible.

example:

```javascript
...
{
  dispose: function (key, value) {
    // key being removed.
  }
}
```
Something is not clear?

**Comment by RiaanJacobs76** [comment]
Perfectly clear thanks, I've tested this in my code and it works how I expected it to. Much appreciated :)
